# Generated by Django 4.2.1 on 2023-06-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=255, unique=True)),
                ('status', models.IntegerField(max_length=255)),
                ('wodne', models.IntegerField(max_length=255)),
                ('wiatrowe', models.IntegerField(max_length=255)),
                ('PV', models.IntegerField(max_length=255)),
                ('generacja', models.IntegerField(max_length=255)),
                ('zapotrzebowanie', models.IntegerField(max_length=255)),
                ('czestotliwosc', models.FloatField(max_length=255)),
                ('inne', models.IntegerField(max_length=255)),
                ('cieplne', models.IntegerField(max_length=255)),
            ],
        ),
    ]
