# Generated by Django 4.2.1 on 2023-06-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='PV',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='cieplne',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='czestotliwosc',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='generacja',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='inne',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='wiatrowe',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='wodne',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='zapotrzebowanie',
            field=models.IntegerField(),
        ),
    ]
