# Generated by Django 4.2.1 on 2023-06-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_property_pv_alter_property_cieplne_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=255, unique=True)),
                ('status', models.IntegerField()),
                ('wodne', models.IntegerField()),
                ('wiatrowe', models.IntegerField()),
                ('PV', models.IntegerField()),
                ('generacja', models.IntegerField()),
                ('zapotrzebowanie', models.IntegerField()),
                ('czestotliwosc', models.FloatField()),
                ('inne', models.IntegerField()),
                ('cieplne', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Property',
        ),
    ]
