# Generated by Django 4.2.1 on 2023-06-09 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_summary_delete_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_id', models.CharField(max_length=255, unique=True)),
                ('timestamp', models.CharField(max_length=255)),
                ('czas', models.DateTimeField(default=datetime.datetime(2023, 6, 9, 13, 53, 24, 93311, tzinfo=datetime.timezone.utc))),
                ('status', models.IntegerField()),
                ('ID', models.CharField(max_length=5)),
                ('wartosc', models.IntegerField()),
                ('rownolegly', models.IntegerField()),
                ('wartosc_plan', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Exchanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=255, unique=True)),
                ('status', models.IntegerField()),
                ('czas', models.DateTimeField(default=datetime.datetime(2023, 6, 9, 13, 53, 24, 93629, tzinfo=datetime.timezone.utc))),
                ('eksport', models.IntegerField()),
                ('_import', models.IntegerField()),
                ('saldo', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='summary',
            name='czas',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 9, 13, 53, 24, 92931, tzinfo=datetime.timezone.utc)),
        ),
    ]
